function asyncGeneratorStep(H,x,N,I,J,G,E){try{var K=H[G](E),F=K.value}catch(O){N(O);return}K.done?x(F):Promise.resolve(F).then(I,J)}function _asyncToGenerator(H){return function(){var x=this,N=arguments;return new Promise(function(I,J){function G(F){asyncGeneratorStep(K,I,J,G,E,"next",F)}function E(F){asyncGeneratorStep(K,I,J,G,E,"throw",F)}var K=H.apply(x,N);G(void 0)})}}
function _typeof(H){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(x){return typeof x}:function(x){return x&&"function"===typeof Symbol&&x.constructor===Symbol&&x!==Symbol.prototype?"symbol":typeof x};return _typeof(H)}var _regenerator;
(function(){var H=function(x){function N(b,a,c,n){a=Object.create((a&&a.prototype instanceof J?a:J).prototype);n=new P(n||[]);a._invoke=O(b,c,n);return a}function I(b,a,c){try{return{type:"normal",arg:b.call(a,c)}}catch(n){return{type:"throw",arg:n}}}function J(){}function G(){}function E(){}function K(b){["next","throw","return"].forEach(function(a){b[a]=function(c){return this._invoke(a,c)}})}function F(b,a){function c(f,w,y,u){f=I(b[f],b,w);if("throw"===f.type)u(f.arg);else{var A=f.arg;return(f=
A.value)&&"object"===_typeof(f)&&B.call(f,"__await")?a.resolve(f.__await).then(function(z){c("next",z,y,u)},function(z){c("throw",z,y,u)}):a.resolve(f).then(function(z){A.value=z;y(A)},function(z){return c("throw",z,y,u)})}}var n;this._invoke=function(f,w){function y(){return new a(function(u,A){c(f,w,u,A)})}return n=n?n.then(y,y):y()}}function O(b,a,c){var n=k;return function(f,w){if(n===d)throw Error("Generator is already running");if(n===h){if("throw"===f)throw w;return T()}c.method=f;for(c.arg=
w;;){if(f=c.delegate)if(f=S(f,c)){if(f===e)continue;return f}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(n===k)throw n=h,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);n=d;f=I(b,a,c);if("normal"===f.type){n=c.done?h:p;if(f.arg===e)continue;return{value:f.arg,done:c.done}}"throw"===f.type&&(n=h,c.method="throw",c.arg=f.arg)}}}function S(b,a){var c=b.iterator[a.method];if(c===v){a.delegate=null;if("throw"===a.method){if(b.iterator["return"]&&
(a.method="return",a.arg=v,S(b,a),"throw"===a.method))return e;a.method="throw";a.arg=new TypeError("The iterator does not provide a 'throw' method")}return e}c=I(c,b.iterator,a.arg);if("throw"===c.type)return a.method="throw",a.arg=c.arg,a.delegate=null,e;c=c.arg;if(!c)return a.method="throw",a.arg=new TypeError("iterator result is not an object"),a.delegate=null,e;if(c.done)a[b.resultName]=c.value,a.next=b.nextLoc,"return"!==a.method&&(a.method="next",a.arg=v);else return c;a.delegate=null;return e}
function U(b){var a={tryLoc:b[0]};1 in b&&(a.catchLoc=b[1]);2 in b&&(a.finallyLoc=b[2],a.afterLoc=b[3]);this.tryEntries.push(a)}function Q(b){var a=b.completion||{};a.type="normal";delete a.arg;b.completion=a}function P(b){this.tryEntries=[{tryLoc:"root"}];b.forEach(U,this);this.reset(!0)}function R(b){if(b){var a=b[r];if(a)return a.call(b);if("function"===typeof b.next)return b;if(!isNaN(b.length)){var c=-1;a=function f(){for(;++c<b.length;)if(B.call(b,c))return f.value=b[c],f.done=!1,f;f.value=
v;f.done=!0;return f};return a.next=a}}return{next:T}}function T(){return{value:v,done:!0}}var C=Object.prototype,B=C.hasOwnProperty,v,q="function"===typeof Symbol?Symbol:{},r=q.iterator||"@@iterator",l=q.asyncIterator||"@@asyncIterator",m=q.toStringTag||"@@toStringTag";x.wrap=N;var k="suspendedStart",p="suspendedYield",d="executing",h="completed",e={};q={};q[r]=function(){return this};var g=Object.getPrototypeOf;(g=g&&g(g(R([]))))&&g!==C&&B.call(g,r)&&(q=g);var t=E.prototype=J.prototype=Object.create(q);
G.prototype=t.constructor=E;E.constructor=G;E[m]=G.displayName="GeneratorFunction";x.isGeneratorFunction=function(b){return(b="function"===typeof b&&b.constructor)?b===G||"GeneratorFunction"===(b.displayName||b.name):!1};x.mark=function(b){Object.setPrototypeOf?Object.setPrototypeOf(b,E):(b.__proto__=E,m in b||(b[m]="GeneratorFunction"));b.prototype=Object.create(t);return b};x.awrap=function(b){return{__await:b}};K(F.prototype);F.prototype[l]=function(){return this};x.AsyncIterator=F;x.async=function(b,
a,c,n,f){void 0===f&&(f=Promise);var w=new F(N(b,a,c,n),f);return x.isGeneratorFunction(a)?w:w.next().then(function(y){return y.done?y.value:w.next()})};K(t);t[m]="Generator";t[r]=function(){return this};t.toString=function(){return"[object Generator]"};x.keys=function(b){var a=[],c;for(c in b)a.push(c);a.reverse();return function f(){for(;a.length;){var w=a.pop();if(w in b)return f.value=w,f.done=!1,f}f.done=!0;return f}};x.values=R;P.prototype={constructor:P,reset:function(b){this.next=this.prev=
0;this.sent=this._sent=v;this.done=!1;this.delegate=null;this.method="next";this.arg=v;this.tryEntries.forEach(Q);if(!b)for(var a in this)"t"===a.charAt(0)&&B.call(this,a)&&!isNaN(+a.slice(1))&&(this[a]=v)},stop:function(){this.done=!0;var b=this.tryEntries[0].completion;if("throw"===b.type)throw b.arg;return this.rval},dispatchException:function(b){function a(A,z){w.type="throw";w.arg=b;c.next=A;z&&(c.method="next",c.arg=v);return!!z}if(this.done)throw b;for(var c=this,n=this.tryEntries.length-1;0<=
n;--n){var f=this.tryEntries[n],w=f.completion;if("root"===f.tryLoc)return a("end");if(f.tryLoc<=this.prev){var y=B.call(f,"catchLoc"),u=B.call(f,"finallyLoc");if(y&&u){if(this.prev<f.catchLoc)return a(f.catchLoc,!0);if(this.prev<f.finallyLoc)return a(f.finallyLoc)}else if(y){if(this.prev<f.catchLoc)return a(f.catchLoc,!0)}else if(u){if(this.prev<f.finallyLoc)return a(f.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(b,a){for(var c=this.tryEntries.length-
1;0<=c;--c){var n=this.tryEntries[c];if(n.tryLoc<=this.prev&&B.call(n,"finallyLoc")&&this.prev<n.finallyLoc){var f=n;break}}f&&("break"===b||"continue"===b)&&f.tryLoc<=a&&a<=f.finallyLoc&&(f=null);c=f?f.completion:{};c.type=b;c.arg=a;return f?(this.method="next",this.next=f.finallyLoc,e):this.complete(c)},complete:function(b,a){if("throw"===b.type)throw b.arg;"break"===b.type||"continue"===b.type?this.next=b.arg:"return"===b.type?(this.rval=this.arg=b.arg,this.method="return",this.next="end"):"normal"===
b.type&&a&&(this.next=a);return e},finish:function(b){for(var a=this.tryEntries.length-1;0<=a;--a){var c=this.tryEntries[a];if(c.finallyLoc===b)return this.complete(c.completion,c.afterLoc),Q(c),e}},"catch":function(b){for(var a=this.tryEntries.length-1;0<=a;--a){var c=this.tryEntries[a];if(c.tryLoc===b){b=c.completion;if("throw"===b.type){var n=b.arg;Q(c)}return n}}throw Error("illegal catch attempt");},delegateYield:function(b,a,c){this.delegate={iterator:R(b),resultName:a,nextLoc:c};"next"===this.method&&
(this.arg=v);return e}};return x}("object"===("undefined"===typeof module?"undefined":_typeof(module))?module.exports:{});try{_regenerator=H}catch(x){Function("r","_regenerator = r")(H)}})();
(function(){function H(){H=_asyncToGenerator(_regenerator.mark(function r(q){return _regenerator.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:return jQuery(q).attr("disabled",!0),l.prev=1,l.next=4,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"LogClear",{}),type:"POST",data:"",dataType:"json",cache:!1});case 4:l.next=8;break;case 6:l.prev=6,l.t0=l["catch"](1);case 8:jQuery(q).attr("disabled",!1);case 9:case "end":return l.stop()}},r,this,[[1,6]])}));
return H.apply(this,arguments)}function x(){x=_asyncToGenerator(_regenerator.mark(function l(q,r){var m,k,p,d,h,e;return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:m=jQuery(q.parentNode).closest(".blck").first();k=m.find(".seraph_accel_spinner");m.find(".content");p=m.find('input[type="button"]:not(.cancel)');d=m.find('input[type="button"].cancel');if(!r){g.next=23;break}p.prop("disabled",!0);k.show();seraph_accel.Manager._int.notRefreshStat=!0;h=null;g.prev=10;g.next=13;return jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"UpdateStatBegin",{}),cache:!1,dataType:"json"});case 13:e=g.sent;seraph_accel.Gen.hr.Fail(e)&&(h=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),e));g.next=20;break;case 17:g.prev=17,g.t0=g["catch"](10),h="HTTP "+g.t0.status;case 20:return h&&(alert(h),p.prop("disabled",!1),k.hide()),delete seraph_accel.Manager._int.notRefreshStat,g.abrupt("return");case 23:return d.prop("disabled",!0),seraph_accel.Manager._int.notRefreshStat=!0,h=null,g.prev=26,g.next=29,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"UpdateStatCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 29:e=g.sent;seraph_accel.Gen.hr.Fail(e)&&(h=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),e));g.next=37;break;case 33:g.prev=33,g.t1=g["catch"](26),h="HTTP "+g.t1.status,d.prop("disabled",!1);case 37:h&&alert(h),delete seraph_accel.Manager._int.notRefreshStat;case 39:case "end":return g.stop()}},l,this,[[10,17],[26,33]])}));return x.apply(this,arguments)}function N(v){switch(v){case 0:return C("OpDescr_Invalidate",
"admin.Manage","seraphinite-accelerator");case 3:return C("OpDescr_CheckInvalidate","admin.Manage","seraphinite-accelerator");case 2:return C("OpDescr_Delete","admin.Manage","seraphinite-accelerator");case 10:return C("OpDescr_SrvDel","admin.Manage","seraphinite-accelerator")}return""+v}function I(){I=_asyncToGenerator(_regenerator.mark(function r(q){var l,m,k,p;return _regenerator.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return l=jQuery(q.parentNode).closest(".blck").first(),m=l.find('input[type="button"].cancel'),
m.prop("disabled",!0),k=null,d.prev=4,d.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"PostUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:p=d.sent;seraph_accel.Gen.hr.Fail(p)&&(k=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),p));d.next=14;break;case 11:d.prev=11,d.t0=d["catch"](4),k="HTTP "+d.t0.status;case 14:k&&alert(k);case 15:case "end":return d.stop()}},r,this,[[4,11]])}));return I.apply(this,arguments)}function J(){J=
_asyncToGenerator(_regenerator.mark(function r(q){var l,m,k,p;return _regenerator.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return l=jQuery(q.parentNode).closest(".blck").first(),m=l.find('input[type="button"].cancel'),m.prop("disabled",!0),k=null,d.prev=4,d.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ScheUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:p=d.sent;seraph_accel.Gen.hr.Fail(p)&&(k=B(C("OpSrvErr_%1$08X",
"admin.Manage","seraphinite-accelerator"),p));d.next=14;break;case 11:d.prev=11,d.t0=d["catch"](4),k="HTTP "+d.t0.status;case 14:k&&alert(k);case 15:case "end":return d.stop()}},r,this,[[4,11]])}));return J.apply(this,arguments)}function G(){G=_asyncToGenerator(_regenerator.mark(function r(q){var l,m,k,p,d,h;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return l=jQuery(q.parentNode).closest(".blck").first(),m=l.find(".seraph_accel_spinner"),k=l.find('input[type="button"]:not(.cancel)'),
p=l.find('input[type="button"].cancel'),m.show(),k.prop("disabled",!0),p.prop("disabled",!1),seraph_accel.Manager._int.notRefreshExtDp=!0,d=null,e.prev=9,e.next=12,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ExtDbUpdBegin",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 12:h=e.sent;seraph_accel.Gen.hr.Fail(h)&&(d=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),h));e.next=19;break;case 16:e.prev=16,e.t0=e["catch"](9),d="HTTP "+e.t0.status;
case 19:d&&alert(d),delete seraph_accel.Manager._int.notRefreshExtDp;case 21:case "end":return e.stop()}},r,this,[[9,16]])}));return G.apply(this,arguments)}function E(){E=_asyncToGenerator(_regenerator.mark(function r(q){var l,m,k,p;return _regenerator.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return l=jQuery(q.parentNode).closest(".blck").first(),m=l.find('input[type="button"].cancel'),m.prop("disabled",!0),k=null,d.prev=4,d.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"ExtDbUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:p=d.sent;seraph_accel.Gen.hr.Fail(p)&&(k=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),p));d.next=14;break;case 11:d.prev=11,d.t0=d["catch"](4),k="HTTP "+d.t0.status;case 14:k&&alert(k);case 15:case "end":return d.stop()}},r,this,[[4,11]])}));return E.apply(this,arguments)}function K(){K=_asyncToGenerator(_regenerator.mark(function m(q,r,l){var k,p,d,h,e,g,t,b,a,c,n,f,w,y;return _regenerator.wrap(function(u){for(;;)switch(u.prev=
u.next){case 0:return k=jQuery(q.parentNode).closest(".blck").first(),p=k.find(".seraph_accel_spinner"),d=k.find(".descr"),h=k.find('input[type="button"]:not(.cancel)'),e=k.find('input[type="button"].cancel'),g=k.find("#seraph_accel_views"),t=k.find("#seraph_accel_geos"),b=[],g.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(g.get()),b=seraph_accel.Ui.TokensList.GetVal(g.get())),a=[],t.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(t.get()),a=seraph_accel.Ui.TokensList.GetVal(t.get())),n=String(k.find(".type").val()),
"uri"===n?c=k.find(".uri").val():0===n.indexOf("uri:")&&(c=n.substr(4),n="uri"),c=seraph_accel.Gen.StrReplaceAll(String(c),["\r","\n","*"],["",";","{ASTRSK}"]),p.show(),d.show(),d.text(N(r)),h.prop("disabled",!0),e.prop("disabled",!1),seraph_accel.Manager._int.notRefreshOp=!0,f={cache:!1,dataType:"json"},512>c.length?f.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",{type:n,op:r,uri:c,v:b.join(),g:a.length?a.join():void 0,_wpnonce:l}):(f.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"CacheOpBegin",{type:n,op:r,v:b.join(),g:a.length?a.join():void 0,_wpnonce:l}),f.type="POST",f.contentType="application/x-www-form-urlencoded",f.data="uri="+encodeURIComponent(c)),w=null,u.prev=23,u.next=26,jQuery.ajax(f);case 26:y=u.sent;seraph_accel.Gen.hr.Fail(y)&&(w=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),y));u.next=33;break;case 30:u.prev=30,u.t0=u["catch"](23),w="HTTP "+u.t0.status;case 33:w&&alert(w),delete seraph_accel.Manager._int.notRefreshOp;case 35:case "end":return u.stop()}},
m,this,[[23,30]])}));return K.apply(this,arguments)}function F(){F=_asyncToGenerator(_regenerator.mark(function m(q,r,l){var k,p,d,h;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return k=jQuery(q.parentNode).closest(".blck").first(),p=k.find('input[type="button"].cancel'),p.prop("disabled",!0),d=null,e.prev=4,e.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpCancel",{op:r,_wpnonce:l}),type:"POST",data:"",cache:!1,dataType:"json"});
case 7:h=e.sent;seraph_accel.Gen.hr.Fail(h)&&(d=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),h));e.next=14;break;case 11:e.prev=11,e.t0=e["catch"](4),d="HTTP "+e.t0.status;case 14:d&&alert(d);case 15:case "end":return e.stop()}},m,this,[[4,11]])}));return F.apply(this,arguments)}function O(){O=_asyncToGenerator(_regenerator.mark(function m(q,r,l){var k,p,d,h,e;return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:return k=jQuery(q.parentNode).closest(".blck").first(),
p=k.find(".seraph_accel_spinner"),d=k.find('input[type="button"]'),p.show(),d.prop("disabled",!0),seraph_accel.Manager._int.notRefreshQueueDeleting=!0,h=null,g.prev=7,g.next=10,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"QueueDelete",{allSites:r?!0:void 0,_wpnonce:l}),type:"GET",cache:!1,dataType:"json"});case 10:e=g.sent;seraph_accel.Gen.hr.Fail(e)&&(h=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),e));g.next=17;break;case 14:g.prev=14,
g.t0=g["catch"](7),h="HTTP "+g.t0.status;case 17:h&&(alert(h),p.hide(),d.prop("disabled",!1)),delete seraph_accel.Manager._int.notRefreshQueueDeleting;case 19:case "end":return g.stop()}},m,this,[[7,14]])}));return O.apply(this,arguments)}function S(){S=_asyncToGenerator(_regenerator.mark(function m(q,r,l){var k,p,d,h,e;return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:return k=jQuery(q.parentNode).closest(".blck").first(),p=k.find(".seraph_accel_spinner"),d=k.find('input[type="button"]'),
p.show(),d.prop("disabled",!0),seraph_accel.Manager._int.notRefreshQueueDeleting=!0,h=null,g.prev=7,g.next=10,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"QueuePause",{v:r,_wpnonce:l}),type:"POST",cache:!1,dataType:"json"});case 10:e=g.sent;seraph_accel.Gen.hr.Fail(e)&&(h=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),e));g.next=17;break;case 14:g.prev=14,g.t0=g["catch"](7),h="HTTP "+g.t0.status;case 17:h&&(alert(h),p.hide(),d.prop("disabled",
!1)),delete seraph_accel.Manager._int.notRefreshQueueDeleting;case 19:case "end":return g.stop()}},m,this,[[7,14]])}));return S.apply(this,arguments)}function U(){U=_asyncToGenerator(_regenerator.mark(function m(q,r,l){var k,p,d,h,e;return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:if(confirm(C("ItemCancelConfirm","admin.Manage_Queue","seraphinite-accelerator"))){g.next=2;break}return g.abrupt("return");case 2:return k=jQuery(q.parentNode).closest(".blck").first(),p=k.find(".seraph_accel_spinner"),
d=k.find('input[type="button"]'),p.show(),d.prop("disabled",!0),seraph_accel.Manager._int.notRefreshQueueDeleting=!0,h=null,g.prev=9,g.next=12,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"QueueItemCancel",{pc:r,_wpnonce:l}),type:"GET",cache:!1,dataType:"json"});case 12:e=g.sent;seraph_accel.Gen.hr.Fail(e)&&(h=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),e));g.next=19;break;case 16:g.prev=16,g.t0=g["catch"](9),h="HTTP "+g.t0.status;case 19:h&&
alert(h),p.hide(),d.prop("disabled",!1),delete seraph_accel.Manager._int.notRefreshQueueDeleting;case 23:case "end":return g.stop()}},m,this,[[9,16]])}));return U.apply(this,arguments)}function Q(){Q=_asyncToGenerator(_regenerator.mark(function l(q,r){var m,k,p,d;return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:d=function(){d=_asyncToGenerator(_regenerator.mark(function g(){return _regenerator.wrap(function(t){for(;;)switch(t.prev=t.next){case 0:return t.next=2,seraph_accel.Manager._int.OnDataRefresh(q,
r);case 2:k();case 3:case "end":return t.stop()}},g,this)}));return d.apply(this,arguments)},p=function(){return d.apply(this,arguments)},k=function(){var e=1E3*parseInt(m.val(),10);100>e&&(e=100);clearTimeout(seraph_accel.Manager._int.refreshTimer);seraph_accel.Manager._int.refreshTimer=setTimeout(p,e)},m=jQuery(q).find("#queue .tmDataRefresh"),m.on("change",k),p();case 6:case "end":return h.stop()}},l,this)}));return Q.apply(this,arguments)}function P(){P=_asyncToGenerator(_regenerator.mark(function l(q,
r){var m,k,p,d,h,e,g,t,b,a,c,n,f,w,y,u,A,z,L,D,V;return _regenerator.wrap(function(M){for(;;)switch(M.prev=M.next){case 0:return m=jQuery(q).find("#status").first(),k=jQuery(q).find("#stat").first(),p=k.find(".seraph_accel_spinner"),d=k.find('input[type="button"]:not(.cancel)'),h=k.find('input[type="button"].cancel'),e=jQuery(q).find("#operate").first(),g=e.find(".seraph_accel_spinner"),t=e.find(".descr"),b=e.find('input[type="button"]:not(.cancel)'),a=e.find('input[type="button"].cancel'),c=jQuery(q).find("#queue").first(),
n=c.find(".content"),f=c.find(".maxItems"),w=c.find(".seraph_accel_spinner"),y=c.find('input[type="button"]'),u=c.find(".descrNums"),M.prev=16,M.next=19,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"GetData",{nMaxQueueItems:f.val(),allSites:r?!0:void 0}),type:"GET",cache:!1,dataType:"json"});case 19:D=M.sent;M.next=24;break;case 22:M.prev=22,M.t0=M["catch"](16);case 24:if(D){M.next=26;break}return M.abrupt("return");case 26:if(!r){for(V in D.status.cont)m.find('[data-id-cont="'+
V+'"]').html(D.status.cont[V]);seraph_accel.Manager._int.notRefreshPostUpd||(A=m.find(".blck.postupd .seraph_accel_spinner"),z=m.find('.blck.postupd input[type="button"]:not(.cancel)'),L=m.find('.blck.postupd input[type="button"].cancel'),D.status.postUpd?(A.show(),z.prop("disabled",!0),L.prop("disabled",!1)):(A.hide(),z.prop("disabled",!1),L.prop("disabled",!0)));seraph_accel.Manager._int.notRefreshScheUpd||(A=m.find(".blck.scheupd .seraph_accel_spinner"),z=m.find('.blck.scheupd input[type="button"]:not(.cancel)'),
L=m.find('.blck.scheupd input[type="button"].cancel'),D.status.scheUpd?(A.show(),z.prop("disabled",!0),L.prop("disabled",!1)):(A.hide(),z.prop("disabled",!1),L.prop("disabled",!0)));seraph_accel.Manager._int.notRefreshCleanup||(A=m.find(".blck.cleanup .seraph_accel_spinner"),z=m.find('.blck.cleanup input[type="button"]:not(.cancel)'),L=m.find('.blck.cleanup input[type="button"].cancel'),D.status.cleanUp?(A.show(),z.prop("disabled",!0),L.prop("disabled",!1)):(A.hide(),z.prop("disabled",!1),L.prop("disabled",
!0)))}r||seraph_accel.Manager._int.notRefreshExtDp||(A=m.find(".blck.extdb .seraph_accel_spinner"),z=m.find('.blck.extdb input[type="button"]:not(.cancel)'),L=m.find('.blck.extdb input[type="button"].cancel'),D.extDb.isUpdating?(A.show(),z.prop("disabled",!0),L.prop("disabled",!1)):(A.hide(),z.prop("disabled",!1),L.prop("disabled",!0)));r||seraph_accel.Manager._int.notRefreshStat||(D.stat.isUpdating?(p.show(),d.prop("disabled",!0),h.prop("disabled",!1)):(p.hide(),d.prop("disabled",!1),h.prop("disabled",
!0)),k.find('[data-id-cont="stat"]').html(D.stat.cont));r||seraph_accel.Manager._int.notRefreshOp||(null===D.curOp&&(D.curOp=void 0),void 0!==D.curOp?(g.show(),t.show(),t.text(N(D.curOp)),b.prop("disabled",!0),a.prop("disabled",!1)):(g.hide(),t.hide(),b.prop("disabled",!1),a.prop("disabled",!0),t.text("")));n.html(D.queue.content);u.text(B(C("QueueNumsDescr_%1$u%2$u","admin.Manage","seraphinite-accelerator"),D.queue.nums.nInitial,D.queue.nums.nInProgress));seraph_accel.Manager._int.notRefreshQueueDeleting||
(w.hide(),y.prop("disabled",!1),D.queue.isPaused?(c.find('input[type="button"].pause').hide(),c.find('input[type="button"].resume').show()):(c.find('input[type="button"].pause').show(),c.find('input[type="button"].resume').hide()));case 33:case "end":return M.stop()}},l,this,[[16,22]])}));return P.apply(this,arguments)}function R(){R=_asyncToGenerator(_regenerator.mark(function r(q){var l,m,k,p,d,h,e,g;return _regenerator.wrap(function(t){for(;;)switch(t.prev=t.next){case 0:return l=jQuery(q.parentNode).closest(".blck").first(),
m=l.find(".url"),k=l.find(".messages"),p=l.find(".seraph_accel_spinner"),d=l.find('input[type="button"]'),h=0,l.find(".liteChk").prop("checked")&&(h|=1),l.find(".medChk").prop("checked")&&(h|=2),l.find(".tidyChk").prop("checked")&&(h|=524288),k.empty(),p.show(),d.prop("disabled",!0),t.prev=12,t.next=15,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"HtmlCheck",{url:m.val(),norm:h}),type:"POST",data:"",dataType:"json",cache:!1});case 15:e=t.sent;t.next=21;break;
case 18:t.prev=18,t.t0=t["catch"](12),e={err:t.t0.statusText};case 21:p.hide();d.prop("disabled",!1);if(!e.err){t.next=26;break}k.append(seraph_accel.Ui.LogItem("error",e.err));return t.abrupt("return");case 26:for(g in e.list)g=e.list[g],k.append(seraph_accel.Ui.LogItem(g.severity,g.text));case 27:case "end":return t.stop()}},r,this,[[12,18]])}));return R.apply(this,arguments)}var T=seraph_accel.Wp.Loc.GetApi(),C=T._x,B=T.sprintf;seraph_accel.Settings={_int:{OnUpdateCssAuto:function(v){seraph_accel.Ui.ComboShowDependedItems(v,
jQuery(v.parentNode).closest(".blck").first().get(0))},OnLogClear:function(v){return H.apply(this,arguments)}}};seraph_accel.Manager={_int:{OnStatOp:function(v,q){return x.apply(this,arguments)},OnCacheOp:function(v,q,r){return K.apply(this,arguments)},OnCacheOpCancel:function(v,q,r){return F.apply(this,arguments)},OnPostUpdCancel:function(v){return I.apply(this,arguments)},OnScheUpdCancel:function(v){return J.apply(this,arguments)},OnExtDbUpdBegin:function(v){return G.apply(this,arguments)},OnExtDbUpdCancel:function(v){return E.apply(this,
arguments)},OnQueueDel:function(v,q,r){return O.apply(this,arguments)},OnQueuePause:function(v,q,r){return S.apply(this,arguments)},OnQueueItemCancel:function(v,q,r){return U.apply(this,arguments)},OnDataRefreshInit:function(v,q){return Q.apply(this,arguments)},OnDataRefresh:function(v,q){return P.apply(this,arguments)},OnHtmlCheck:function(v){return R.apply(this,arguments)}}};(function(){function v(m){return q.apply(this,arguments)}function q(){q=_asyncToGenerator(_regenerator.mark(function p(k){var d,
h;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return d={},e.prev=1,seraph_accel.SelfDiag._int.curAjax=jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"SelfDiag_"+k,{}),cache:!1,dataType:"json"}),e.next=5,seraph_accel.SelfDiag._int.curAjax;case 5:d=e.sent;delete seraph_accel.SelfDiag._int.curAjax;e.next=14;break;case 9:e.prev=9,e.t0=e["catch"](1),delete seraph_accel.SelfDiag._int.curAjax,0===e.t0.status?d.hr=seraph_accel.Gen.hr.S_ABORTED:
(d.hr=seraph_accel.Gen.hr.E_FAIL,d.descr="HTTP "+e.t0.status),500==e.t0.status&&(h=document.implementation.createHTMLDocument(""),h.documentElement.innerHTML=e.t0.responseText,h=h.body.textContent,h=seraph_accel.Gen.StrReplaceAll(h,"\r",""),h=seraph_accel.Gen.StrReplaceAll(h,["\t","\v"]," "),h=seraph_accel.Gen.StrReplaceAll(h,"\n",". "),(h=seraph_accel.Gen.StrReplaceAllWhileChanging(h,["  ",". . "],[" ",". "]).trim())&&"."!=h&&(d.descr+="<br>"+h));case 14:return e.abrupt("return",d);case 15:case "end":return e.stop()}},
p,this,[[1,9]])}));return q.apply(this,arguments)}function r(){r=_asyncToGenerator(_regenerator.mark(function p(k){var d,h,e,g,t,b,a,c,n,f,w,y=arguments;return _regenerator.wrap(function(u){for(;;)switch(u.prev=u.next){case 0:d=1<y.length&&void 0!==y[1]?y[1]:!1;h=jQuery(k.parentNode).closest(".blck").first();e=h.find(".seraph_accel_spinner");g=h.find('input[type="button"]:not(.cancel)');t=h.find('input[type="button"].cancel');b=h.find(".log");a=[{id:"3rdPartySettCompat",name:l("TestName_3rdPartySettCompat",
"admin.SelfDiag","seraphinite-accelerator")},{id:"AsyncRequest",name:l("TestName_AsyncRequest","admin.SelfDiag","seraphinite-accelerator")},{id:"SetMaxExecTime",name:l("TestName_SetMaxExecTime","admin.SelfDiag","seraphinite-accelerator")},{id:"PageOptimize",name:l("TestName_PageOptimize","admin.SelfDiag","seraphinite-accelerator")},{id:"VendorSrv",name:l("TestName_VendorSrv","admin.SelfDiag","seraphinite-accelerator")},{id:"ExtCache",name:l("TestName_ExtCache","admin.SelfDiag","seraphinite-accelerator")}];
b.empty();for(c=0;c<a.length;c++)n=a[c],b.append(seraph_accel.Ui.LogItem("none",seraph_accel.Ui.Tag("strong",n.name?n.name:n.id),!1));if(!d){u.next=11;break}return u.abrupt("return");case 11:e.show(),g.prop("disabled",!0),t.prop("disabled",!1),seraph_accel.SelfDiag._int.inProgress=!0,c=0;case 16:if(!(c<a.length)){u.next=31;break}n=a[c];jQuery(b.children().get(c)).replaceWith(seraph_accel.Ui.LogItem("info",seraph_accel.Ui.Tag("strong",n.name?n.name:n.id)+l("TestRunning","admin.SelfDiag","seraphinite-accelerator"),
!1));u.next=21;return v(n.id);case 21:f=u.sent;w=l("TestSucc","admin.SelfDiag","seraphinite-accelerator");f.hr!=seraph_accel.Gen.hr.S_OK&&(w=seraph_accel.Gen.hr.Succ(f.hr)?f.hr==seraph_accel.Gen.hr.S_ABORTED?l("TestAbort","admin.SelfDiag","seraphinite-accelerator"):f.hr==seraph_accel.Gen.hr.S_FALSE?l("TestNotice","admin.SelfDiag","seraphinite-accelerator"):l("TestWarn","admin.SelfDiag","seraphinite-accelerator"):l("TestError","admin.SelfDiag","seraphinite-accelerator"));f.descr&&(w+="<br>"+f.descr);
jQuery(b.children().get(c)).replaceWith(seraph_accel.Ui.LogItem(f.hr==seraph_accel.Gen.hr.S_OK?"success":seraph_accel.Gen.hr.Succ(f.hr)?f.hr==seraph_accel.Gen.hr.S_FALSE?"normal":"warning":"error",seraph_accel.Ui.Tag("strong",n.name?n.name:n.id)+w,!1));if(seraph_accel.SelfDiag._int.inProgress){u.next=28;break}return u.abrupt("break",31);case 28:c++;u.next=16;break;case 31:e.hide(),g.prop("disabled",!1),t.prop("disabled",!0);case 34:case "end":return u.stop()}},p,this)}));return r.apply(this,arguments)}
var l=seraph_accel.Wp.Loc.GetApi()._x;seraph_accel.SelfDiag={_int:{OnStart:function(m){return r.apply(this,arguments)},OnCancel:function(m){m=jQuery(m.parentNode).closest(".blck").first();m.find(".seraph_accel_spinner");m.find('input[type="button"]:not(.cancel)');m.find('input[type="button"].cancel').prop("disabled",!0);seraph_accel.SelfDiag._int.inProgress=!1;seraph_accel.SelfDiag._int.curAjax&&seraph_accel.SelfDiag._int.curAjax.abort()},inProgress:!1}}})()})();
